/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsitesRouteImport } from './routes/websites'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AiVideosRouteImport } from './routes/ai-videos'
import { Route as AiSystemsRouteImport } from './routes/ai-systems'
import { Route as AiAvatarsRouteImport } from './routes/ai-avatars'
import { Route as AiAdsRouteImport } from './routes/ai-ads'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogCategoryRouteImport } from './routes/blog.$category'
import { Route as ApiPublicSendContactRouteImport } from './routes/api/public/send-contact'

const WebsitesRoute = WebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AiVideosRoute = AiVideosRouteImport.update({
  id: '/ai-videos',
  path: '/ai-videos',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSystemsRoute = AiSystemsRouteImport.update({
  id: '/ai-systems',
  path: '/ai-systems',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAvatarsRoute = AiAvatarsRouteImport.update({
  id: '/ai-avatars',
  path: '/ai-avatars',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAdsRoute = AiAdsRouteImport.update({
  id: '/ai-ads',
  path: '/ai-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogCategoryRoute = BlogCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => BlogRoute,
} as any)
const ApiPublicSendContactRoute = ApiPublicSendContactRouteImport.update({
  id: '/api/public/send-contact',
  path: '/api/public/send-contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/ai': typeof AiRoute
  '/ai-ads': typeof AiAdsRoute
  '/ai-avatars': typeof AiAvatarsRoute
  '/ai-systems': typeof AiSystemsRoute
  '/ai-videos': typeof AiVideosRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/landing': typeof LandingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/websites': typeof WebsitesRoute
  '/blog/$category': typeof BlogCategoryRoute
  '/blog/': typeof BlogIndexRoute
  '/api/public/send-contact': typeof ApiPublicSendContactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/ai': typeof AiRoute
  '/ai-ads': typeof AiAdsRoute
  '/ai-avatars': typeof AiAvatarsRoute
  '/ai-systems': typeof AiSystemsRoute
  '/ai-videos': typeof AiVideosRoute
  '/contact': typeof ContactRoute
  '/landing': typeof LandingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/websites': typeof WebsitesRoute
  '/blog/$category': typeof BlogCategoryRoute
  '/blog': typeof BlogIndexRoute
  '/api/public/send-contact': typeof ApiPublicSendContactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/ai': typeof AiRoute
  '/ai-ads': typeof AiAdsRoute
  '/ai-avatars': typeof AiAvatarsRoute
  '/ai-systems': typeof AiSystemsRoute
  '/ai-videos': typeof AiVideosRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/landing': typeof LandingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/websites': typeof WebsitesRoute
  '/blog/$category': typeof BlogCategoryRoute
  '/blog/': typeof BlogIndexRoute
  '/api/public/send-contact': typeof ApiPublicSendContactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/ai'
    | '/ai-ads'
    | '/ai-avatars'
    | '/ai-systems'
    | '/ai-videos'
    | '/blog'
    | '/contact'
    | '/landing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/websites'
    | '/blog/$category'
    | '/blog/'
    | '/api/public/send-contact'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/ai'
    | '/ai-ads'
    | '/ai-avatars'
    | '/ai-systems'
    | '/ai-videos'
    | '/contact'
    | '/landing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/websites'
    | '/blog/$category'
    | '/blog'
    | '/api/public/send-contact'
  id:
    | '__root__'
    | '/'
    | '/accessibility'
    | '/ai'
    | '/ai-ads'
    | '/ai-avatars'
    | '/ai-systems'
    | '/ai-videos'
    | '/blog'
    | '/contact'
    | '/landing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/websites'
    | '/blog/$category'
    | '/blog/'
    | '/api/public/send-contact'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AiRoute: typeof AiRoute
  AiAdsRoute: typeof AiAdsRoute
  AiAvatarsRoute: typeof AiAvatarsRoute
  AiSystemsRoute: typeof AiSystemsRoute
  AiVideosRoute: typeof AiVideosRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  LandingRoute: typeof LandingRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  WebsitesRoute: typeof WebsitesRoute
  ApiPublicSendContactRoute: typeof ApiPublicSendContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/websites': {
      id: '/websites'
      path: '/websites'
      fullPath: '/websites'
      preLoaderRoute: typeof WebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-videos': {
      id: '/ai-videos'
      path: '/ai-videos'
      fullPath: '/ai-videos'
      preLoaderRoute: typeof AiVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-systems': {
      id: '/ai-systems'
      path: '/ai-systems'
      fullPath: '/ai-systems'
      preLoaderRoute: typeof AiSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-avatars': {
      id: '/ai-avatars'
      path: '/ai-avatars'
      fullPath: '/ai-avatars'
      preLoaderRoute: typeof AiAvatarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-ads': {
      id: '/ai-ads'
      path: '/ai-ads'
      fullPath: '/ai-ads'
      preLoaderRoute: typeof AiAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$category': {
      id: '/blog/$category'
      path: '/$category'
      fullPath: '/blog/$category'
      preLoaderRoute: typeof BlogCategoryRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/public/send-contact': {
      id: '/api/public/send-contact'
      path: '/api/public/send-contact'
      fullPath: '/api/public/send-contact'
      preLoaderRoute: typeof ApiPublicSendContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogCategoryRoute: typeof BlogCategoryRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogCategoryRoute: BlogCategoryRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityRoute: AccessibilityRoute,
  AiRoute: AiRoute,
  AiAdsRoute: AiAdsRoute,
  AiAvatarsRoute: AiAvatarsRoute,
  AiSystemsRoute: AiSystemsRoute,
  AiVideosRoute: AiVideosRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  LandingRoute: LandingRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  WebsitesRoute: WebsitesRoute,
  ApiPublicSendContactRoute: ApiPublicSendContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
